CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Olympiad" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        year date NOT NULL,
        host_country character varying(100) NOT NULL,
        city character varying(100) NOT NULL,
        is_winter boolean NOT NULL DEFAULT FALSE,
        is_deleted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "Olympiad_pkey" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Participant" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        surname character varying(100) NOT NULL,
        name character varying(50) NOT NULL,
        patronymic character varying(50) NOT NULL,
        birthdate date NOT NULL,
        is_deleted boolean NOT NULL DEFAULT FALSE,
        photo bytea NOT NULL,
        CONSTRAINT "Participant_pkey" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Sport_Type" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "Sport_Type_pkey" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Olympiad_Participant" (
        participant_id integer NOT NULL,
        id integer GENERATED BY DEFAULT AS IDENTITY,
        olympiad_id integer NOT NULL,
        CONSTRAINT "Olympiad_Participant_pkey" PRIMARY KEY (participant_id),
        CONSTRAINT olympiad_fk FOREIGN KEY (olympiad_id) REFERENCES "Olympiad" (id),
        CONSTRAINT participant_fk FOREIGN KEY (participant_id) REFERENCES "Participant" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Sport_Type_Olympiad" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        sport_type_id integer NOT NULL,
        olympiad_id integer NOT NULL,
        CONSTRAINT "Sport_Type_Olympiad_pkey" PRIMARY KEY (id),
        CONSTRAINT "olymp_FK" FOREIGN KEY (olympiad_id) REFERENCES "Olympiad" (id),
        CONSTRAINT "sport_type_FK" FOREIGN KEY (sport_type_id) REFERENCES "Sport_Type" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE TABLE "Sport_Type_Participant" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        sport_type_id integer NOT NULL,
        participant_id integer NOT NULL,
        gold_medals integer NOT NULL DEFAULT 0,
        silver_medals integer NOT NULL DEFAULT 0,
        bronze_medals integer NOT NULL DEFAULT 0,
        CONSTRAINT "Sport_Type_Participant_pkey" PRIMARY KEY (id),
        CONSTRAINT participant_id FOREIGN KEY (participant_id) REFERENCES "Participant" (id),
        CONSTRAINT sport_type_fk FOREIGN KEY (sport_type_id) REFERENCES "Sport_Type" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE INDEX "IX_Olympiad_Participant_olympiad_id" ON "Olympiad_Participant" (olympiad_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE INDEX "IX_Sport_Type_Olympiad_olympiad_id" ON "Sport_Type_Olympiad" (olympiad_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE INDEX "IX_Sport_Type_Olympiad_sport_type_id" ON "Sport_Type_Olympiad" (sport_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE INDEX "IX_Sport_Type_Participant_participant_id" ON "Sport_Type_Participant" (participant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    CREATE INDEX "IX_Sport_Type_Participant_sport_type_id" ON "Sport_Type_Participant" (sport_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211112251_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240211112251_InitialCreate', '8.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211115229_AddParticipantCountryField') THEN
    ALTER TABLE "Participant" ADD country character varying(100) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211115229_AddParticipantCountryField') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240211115229_AddParticipantCountryField', '8.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211120409_AddOlympiadNameField') THEN
    ALTER TABLE "Olympiad" ADD name character varying(100) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240211120409_AddOlympiadNameField') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240211120409_AddOlympiadNameField', '8.0.1');
    END IF;
END $EF$;
COMMIT;

